examenParcial/examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestionTienda/', include('gestionTienda.urls'))
]

examenParcial/gestionTienda/urls.py
from django.urls import path
from . import views

app_name = 'gestionTienda'

urlpatterns = [
    path('', views.index, name='index'),
    path('Productos', views.productos, name='productos'),
    path('Tiendas',views.tiendas, name='tiendas'),
    path('Detalle/<idTienda>', views.detalle, name="detalle"),
    path('EliminarProducto/<idProducto>', views.eliminarProducto, name='eliminarProducto'),
    path('AgregarProducto/<idTienda>', views.agregarProducto, name='agregarProducto'),
    path('EliminarTienda/<idTienda>', views.eliminarTienda, name="eliminarTienda")

]

examenParcial/gestionTienda/models.py
from django.db import models

# Create your models here.
class Tienda(models.Model):
    direccion = models.CharField(max_length=50, blank=True, null=True)
    provincia = models.CharField(max_length=50, blank=True, null=True)
    region = models.CharField(max_length=50, blank=True, null=True)
    fechaCreacion = models.DateField( blank=True, null=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)


class Producto(models.Model):
    descripcion = models.CharField(max_length=50, blank=True, null=True)
    codigo = models.CharField(max_length=50, blank=True, null=True)
    precioVenta = models.FloatField(blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True)
    tiendaRelacionada = models.ForeignKey(Tienda, on_delete=models.SET_NULL, blank=True, null=True)

examenParcial/gestionTienda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Tienda, Producto
from datetime import date

# Create your views here.

def index(request):    
    return HttpResponseRedirect(reverse('gestionTienda:tiendas'))

def productos(request):
    if request.method == 'POST':
        descripcion = request.POST.get('descripcion')
        codigo = request.POST.get('codigo')
        precioVenta = request.POST.get('precioVenta')
        cantidad = request.POST.get('cantidad')
        idTienda = request.POST.get('tienda')
        tienda = Tienda.objects.get(id=idTienda)
        Producto.objects.create(
            descripcion = descripcion,
            codigo = codigo,
            precioVenta = precioVenta,
            cantidad = cantidad,
            tiendaRelacionada = tienda
        )
        return HttpResponseRedirect(reverse('gestionTienda:productos'))

    return render(request, 'productos.html', {
        'listaProductos': Producto.objects.all().order_by('id'),
        'listaTiendas': Tienda.objects.all().order_by('id')
    })

def tiendas(request):
    if request.method=='POST':
        direccionTienda = request.POST.get('direccionTienda')
        provinciaTienda = request.POST.get('provinciaTienda')        
        regionTienda = request.POST.get('regionTienda')
        fechaCreacion = date.today()
        telefonoTienda = request.POST.get('telefonoTienda')
        Tienda.objects.create(
            direccion = direccionTienda,
            provincia = provinciaTienda,
            region = regionTienda,
            fechaCreacion = fechaCreacion,
            telefono = telefonoTienda
        )
        return HttpResponseRedirect(reverse('gestionTienda:tiendas'))    
    return render(request, 'tiendas.html', {
        'listaTiendas': Tienda.objects.all().order_by('id')
    })

def detalle(request, idTienda):   
    tienda = Tienda.objects.get(id=idTienda)
    listaProductosTienda = Producto.objects.all().filter(tiendaRelacionada = tienda)
    return render(request, 'detalle.html',{
        'productosTienda': listaProductosTienda,
        'tienda': tienda,
        'idTienda':idTienda
    })

def eliminarProducto(request, idProducto):
    producto = Producto.objects.get(id=idProducto)
    tienda = producto.tiendaRelacionada
    idTienda = tienda.id
    producto.delete()
    return HttpResponseRedirect(reverse('gestionTienda:detalle',kwargs={'idTienda':idTienda}))

def agregarProducto(request, idTienda):
    if request.method == 'POST':
        descripcion = request.POST.get('descripcion')
        codigo = request.POST.get('codigo')
        precioVenta = request.POST.get('precioVenta')
        cantidad = request.POST.get('cantidad')
        #idTienda = request.POST.get('tienda')
        tienda = Tienda.objects.get(id=idTienda)
        Producto.objects.create(
            descripcion = descripcion,
            codigo = codigo,
            precioVenta = precioVenta,
            cantidad = cantidad,
            tiendaRelacionada = tienda
        )
        return HttpResponseRedirect(reverse('gestionTienda:detalle',kwargs={'idTienda':idTienda}))
    
def eliminarTienda(request, idTienda):
    tienda = Tienda.objects.get(id=idTienda)
    tienda.delete()
    return HttpResponseRedirect(reverse('gestionTienda:tiendas'))




    
        

examenParcial/gestionTienda/templates/detalle.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!--Autor: Edson Miguel Quispe Flores
            Código: 20145950
            Descripción: Vista con una tabla y el detalle de productos registrados para esa tienda. -->
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand">LOGOBAKERY</a>
                <div >
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'gestionTienda:tiendas' %}">Tiendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'gestionTienda:productos' %}">Productos</a>
                        </li>
                    </ul>
    
                </div>
                
            </nav>
        </div>
        <div class="mt-5 text-center">
            <h1>Productos de Tienda: {{ tienda.provincia }} - {{tienda.region}}</h1>
        </div>
        <div class="container mt-5">
            <div class="row">
                <div class="col-4 text-left"><h5>Dirección: {{tienda.direccion}}</h5></div>
                <div class="col-4 text-left"><h5>Fecha Creación: {{tienda.fechaCreacion}}</h5></div>
                <div class="col-4 text-left"><h5>Teléfono: {{tienda.telefono}}</h5></div>
            </div>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Crear Producto <i class="fa-solid fa-plus"></i></button>
                </div>
                <div class="col-2">
                    <a class="btn btn-secondary" role="button" href="{% url 'gestionTienda:tiendas' %}">Regresar <i class="fa-solid fa-arrow-left"></i></a>
                </div>
                
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <table class="table table-responsive table-bordered">
                        <thead class="thead-light">
                            <th class="text-center">Descripción</th>
                            <th class="text-center">Código</th>
                            <th class="text-center">Precio Venta</th>
                            <th class="text-center">Cantidad</th>
                            <th class="text-center">Eliminar Producto</th>
                        </thead>
                        <tbody>
                            {% for producto in productosTienda %}
                            <tr>
                                <td >{{ producto.descripcion }}</td>
                                <td class="text-center">{{ producto.codigo }}</td>
                                <td class="text-center">{{ producto.precioVenta }}</td>
                                <td class="text-center">{{ producto.cantidad }}</td>
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestionTienda:eliminarProducto' producto.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal fade" tabindex="-1" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" action="{% url 'gestionTienda:agregarProducto' idTienda %}">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title">Crear Producto</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row form-group justify-content-center mb-3">
                                
                                <div class="col-5">
                                    <label>Descripción</label>
                                    <input class="form-control" type="text" name="descripcion" required>
                                </div>
                                <div class="col-5">
                                    <label>Código</label>
                                    <input class="form-control" type="text" name="codigo" required>
                                </div>
                                <div class="col-5">
                                    <label>Precio de Venta</label>
                                    <input class="form-control" type="number" name="precioVenta" required>
                                </div>
                                
                                <div class="col-5">
                                    <label>Cantidad</label>
                                    <input class="form-control" type="number" name="cantidad" required>
                                </div>
                                
                                
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Crear Producto</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </body>
</html>

examenParcial/gestionTienda/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!--Autor: Edson Miguel Quispe Flores
            Código: 20145950 -->
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand">LOGOBAKERY</a>
                <div >
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'gestionTienda:tiendas' %}">Tiendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'gestionTienda:productos' %}">Productos</a>
                        </li>
                    </ul>
    
                </div>
                
            </nav>
        </div>
        
            
        
        
    </body>
</html>

examenParcial/gestionTienda/templates/productos.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!--Autor: Edson Miguel Quispe Flores
            Código: 20145950 
            Descripción: Vista con una tabla de productos registradas en la base de datos SQLite.-->
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand">LOGOBAKERY</a>
                <div >
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'gestionTienda:tiendas' %}">Tiendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'gestionTienda:productos' %}">Productos</a>
                        </li>
                    </ul>
    
                </div>
                
            </nav>
        </div>
        <div class="mt-5 text-center">
            <h1>Gestión de Productos</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Crear Producto <i class="fa-solid fa-plus"></i></button>
                </div>
                
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-12 table-responsive">
                    <table class="table table-light table-bordered table-striped">
                        <thead class="thead-light">
                            <th class="text-center">Descripción</th>
                            <th class="text-center">Código</th>
                            <th class="text-center" data-formatter="NumFormatter">Precio Venta</th>
                            <th class="text-center">Cantidad</th>
                            <th class="text-center">Tienda</th>                            
                            <th class="text-center">Eliminar Producto</th>
                        </thead>
                        <tbody>
                            {% for producto in listaProductos %}
                            <tr>
                                <td>{{ producto.descripcion }}</td>
                                <td class="text-center">{{ producto.codigo }}</td>
                                <td class="text-center">{{ producto.precioVenta }}</td>
                                <td class="text-center">{{ producto.cantidad }}</td>
                                <td class="text-center">{{ producto.tiendaRelacionada.provincia }}</td>                                
                                <td class="text-center"><a class="btn btn-danger" href="#"><i class="fa-solid fa-trash"></i></a></td>
                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" action="{% url 'gestionTienda:productos' %}">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title">Crear Producto</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row form-group justify-content-center mb-3">
                                <div class="col-5">
                                    <label>Descripción</label>
                                    <input class="form-control" type="text" name="descripcion" required>
                                </div>
                                <div class="col-5">
                                    <label>Código</label>
                                    <input class="form-control" type="text" name="codigo" required>
                                </div>
                                <div class="col-5">
                                    <label>Precio de Venta</label>
                                    <input class="form-control" type="number" name="precioVenta" required min="0.00" step="0.01">
                                </div>
                                
                                <div class="col-5">
                                    <label>Cantidad</label>
                                    <input class="form-control" type="number" name="cantidad" required min="0">
                                </div>
                                
                                <div class="col-5">
                                    <label>Seleccionar tienda</label>
                                    <select class="form-select" name="tienda" required>
                                        <option value="" selected></option>
                                        {% for tienda in listaTiendas %}
                                        <option value="{{ tienda.id }}">{{ tienda.provincia }} - {{ tienda.region }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Crear Producto</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

examenParcial/gestionTienda/templates/tiendas.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!--Autor: Edson Miguel Quispe Flores
            Código: 20145950 
            Descripción: Vista con una tabla de tiendas registradas en la base de datos SQLite. -->
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand">LOGOBAKERY</a>
                <div >
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'gestionTienda:tiendas' %}">Tiendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'gestionTienda:productos' %}">Productos</a>
                        </li>
                    </ul>
    
                </div>
                
            </nav>
        </div>
        <div class="mt-5 text-center">
            <h1>Gestión de Tiendas</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaTienda">Crear Tienda <i class="fa-solid fa-plus"></i></button>
                </div>
                
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <table class="table table-responsive table-bordered table-striped">
                        <thead class="thead-light">
                            <th class="text-center">Dirección</th>
                            <th class="text-center">Provincia</th>
                            <th class="text-center">Región</th>
                            <th class="text-center">Fecha Creación</th>
                            <th class="text-center">Teléfono</th>
                            <th class="text-center">Ver Productos</th>
                            <th class="text-center">Eliminar Tienda</th>
                        </thead>
                        <tbody>
                            {% for tienda in listaTiendas %}
                            <tr>
                                <td>{{ tienda.direccion }}</td>
                                <td class="text-center">{{ tienda.provincia }}</td>
                                <td class="text-center">{{ tienda.region }}</td>
                                <td class="text-center">{{ tienda.fechaCreacion }}</td>
                                <td class="text-center">{{ tienda.telefono }}</td>
                                <td class="text-center"><a class="btn btn-info" href="{% url 'gestionTienda:detalle' tienda.id %}"><i class="fa-solid fa-eye"></i></a></td>
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestionTienda:eliminarTienda' tienda.id %}"><i class="fa-solid fa-trash"></i></a></td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" id="nuevaTienda" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" action="{% url 'gestionTienda:tiendas' %}">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title">Crear Tienda</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row form-group justify-content-center mb-3">
                                <div class="col-5">
                                    <label>Direccion</label>
                                    <input class="form-control" type="text" name="direccionTienda" required>
                                </div>
                                <div class="col-5">
                                    <label>Provincia</label>
                                    <input class="form-control" type="text" name="provinciaTienda" required>
                                </div>
                                <div class="col-5">
                                    <label>Region</label>
                                    <input class="form-control" type="text" name="regionTienda" required>
                                </div>
                                
                                <div class="col-5">
                                    <label>Telefono</label>
                                    <input class="form-control" type="number" name="telefonoTienda" required>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Crear Tienda</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>

</html>